INSERT INTO USER (ID, USER, PASSWORD) VALUES (1, 'blah', 'blah');
INSERT INTO USER (ID, USER, PASSWORD) VALUES (2, 'blah2', 'blah2');
INSERT INTO USER (ID, USER, PASSWORD) VALUES (3, 'blah3', 'blah3');
