#  port: 10071
server:
  port: ${PORT:10071}

spring:
  cloud:
    config:
      server:
        git:
          # nb: Must be a root level folder (e.g. in root of repo at github)
          uri: https://github.com/micklove/sample-config
      name: ci-config-service
