#  port: 10071
server:
  port: ${PORT:10071}

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/joshlong/spring-doge-microservice-configuration
          #uri: https://github.com/micklove/config-server/tree/master/config
      name: ci-config-service
